CREATE DATABASE dbGradebook;

USE dbGradebook;

CREATE TABLE Person(
  ID_Person INT AUTO_INCREMENT PRIMARY KEY,
  E_Mail VARCHAR(255),
  Passwort CHAR(32)
);

CREATE TABLE Semester(
  ID_Semester INT AUTO_INCREMENT PRIMARY KEY,
  SemesterName VARCHAR(255),
  Person_ID INT,
  SemesterModul_ID INT,
  FOREIGN KEY (Person_ID) REFERENCES Person(ID_Person) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Modul(
  ID_Modul INT AUTO_INCREMENT PRIMARY KEY,
  ModulName VARCHAR(255),
  SemesterModul_ID INT
);

CREATE TABLE Test(
  ID_Test INT AUTO_INCREMENT PRIMARY KEY,
  Test DOUBLE(3,2),
  TestPfad VARCHAR(255),
  Modul_ID INT,
  FOREIGN KEY (Modul_ID) REFERENCES Modul(ID_Modul) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SemesterModul(
  ID_SemesterModul INT AUTO_INCREMENT PRIMARY KEY,
  Semester_ID INT,
  Modul_ID INT,
  FOREIGN KEY (Semester_ID) REFERENCES Semester(ID_Semester) ON UPDATE CASCADE ON DELETE CASCADE ,
  FOREIGN KEY (Modul_ID) REFERENCES Modul(ID_Modul) ON UPDATE CASCADE ON DELETE CASCADE
);






